services:
  prometheus:
    container_name: prometheus-ctr
    image: prom/prometheus:v2.51.2
    restart: unless-stopped
    ports:
      - '9090:9090'
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./platform/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana-ctr
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    user: "472"
    ports:
      - '3000:3000'
    volumes:
      - ./platform/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./platform/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./platform/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./platform/tempo/tempo.yml:/etc/tempo.yml
    ports:
      - '3200:3200'   # tempo
      - '9411:9411'  # zipkin

  loki:
    image: grafana/loki:latest
    container_name: loki
    command:
      - -config.file=/etc/loki/local-config.yaml
    ports:
      - '3100:3100'

  api-gateway:
    image: api-gateway:0.0.1
    container_name: api-gateway
    ports:
      - 9000:9000
    environment:
      BOOK_SERVICE_URI: book-service
      LOKI_URI: http://loki:3100/loki/api/v1/push
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411
      SPRING_DATA_REDIS_HOST: redis

  book-service:
    image: book-service:0.0.1
    container_name: book-service
    ports:
      - 9001:9001
    environment:
      LOKI_URI: http://loki:3100/loki/api/v1/push
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411