spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: book-route
          uri: http://${BOOK_SERVICE_URI:localhost}:9001
          predicates:
            - Path=/books/**
          filters:
            - AddRequestHeader=X-Tenant-ID,acme
            - AddResponseHeader=X-Genre,fantasy
            - name: Retry
              args:
                retries: 3
                methods: GET
                backoff:
                  firstBackoff: 500ms
                  maxBackoff: 2s
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10 # how many requests per second to allow (without any dropped requests). This is the rate at which the token bucket is filled.
              burstCapacity: 20 # maximum number of requests a user is allowed in a single second (without any dropped requests). This is the number of tokens the token bucket can hold. Setting this value to zero blocks all requests.
              requestedTokens: 1 # how many tokens a request costs. This is the number of tokens taken from the bucket for each request and defaults to 1.

server:
  port: 9000

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: info
    org.springframework.cloud.gateway: trace


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 10s

  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true